###
POST http://localhost:3000/post
Content-Type: application/json

{
    "title": "Post",
    "content": "content of my first post",
    "sender": "noy19988"
}


###
GET http://localhost:3000/post


###
GET http://localhost:3000/post/1


###
PUT http://localhost:3000/post/1
Content-Type: application/json

{
    "title": "Updated Title",
    "content": "Updated content"
}



###
GET http://localhost:3000/post/search?sender=user123



###
POST http://localhost:3000/comment
Content-Type: application/json

{
    "postId": "1",
    "content": "good post",
    "author": "ron22"
}



###
GET http://localhost:3000/comment/post/1



###
PUT http://localhost:3000/comment/1
Content-Type: application/json

{
    "content": "Updated content"
}



###
DELETE http://localhost:3000/comment/1

###
DELETE http://localhost:3000/post/6776d1afaf0b5f10583777e4

