###
POST http://localhost:3000/post
Content-Type: application/json

{
    "title": "presen posttts",
    "content": "content of my present posttst",
    "sender": "eliav"
}


###
GET http://localhost:3000/post


###n
GET http://localhost:3000/post/677700e81e5efd44e9e3a15e

###
GET http://localhost:3000/post?sender=eliav


###
PUT http://localhost:3000/post/677700e81e5efd44e9e3a15e
Content-Type: application/json

{
    "title": "Updated Tללitle",
    "content": "Updated content"
}









###
POST http://localhost:3000/comment
Content-Type: application/json

{
    "postId": "1",
    "content": "good post",
    "author": "ron22"
}



###
GET http://localhost:3000/comment/post/1



###
PUT http://localhost:3000/comment/1
Content-Type: application/json

{
    "content": "Updated content"
}



###
DELETE http://localhost:3000/comment/1

###
DELETE http://localhost:3000/post/6776d1afaf0b5f10583777e4


### Register a new user
POST http://localhost:3000/users/register
Content-Type: application/json

{
  "username": "noy123456666666",
  "email": "noy1234@gmail.commm",
  "password": "1212"
}

### Login a user
POST http://localhost:3000/users/login
Content-Type: application/json

{
  
  "email": "noy1234@gmail.comm",
  "password": "1212"
}


### Get all users
GET http://localhost:3000/users
Authorization: Bearer <your_token_here>


### Logout a user
POST http://localhost:3000/users/logout
Content-Type: application/json

{
  "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NzdlYjY0OGUxNWUwMDliYWM0M2E1ZTYiLCJpYXQiOjE3MzYzNTkzMDAsImV4cCI6MTczNjk2NDEwMH0.6J1Cc9u6EbcyD8h6HGSHmP7r-9R3EN-4_ipkjcdsKqE"
}

### Refresh a user token

POST http://localhost:3000/users/refresh
Content-Type: application/json

{
  "refreshToken": "<your_refresh_token_here>"
}

### Create a new post with an access token
POST http://localhost:3000/post
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NzdlNjU1MjYyNGY1NGUyMmM3ZTkwNTUiLCJpYXQiOjE3MzYzMzY3NDMsImV4cCI6MTczNjU5NTk0M30.M74BCx0zlZWeLIVh7td0LQjtLDB5KezBsJs51Q0n9nE

{
  "title": "My First Post",
  "content": "This is the content of my first post.",
  "author": "677a8d259fe1036c9b6ea27f"
}


### update a post with an access token

PUT http://localhost:3000/post/677a8a8ec74320900f37d65b
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NzdlNjU1MjYyNGY1NGUyMmM3ZTkwNTUiLCJpYXQiOjE3MzYzMzY3NDMsImV4cCI6MTczNjU5NTk0M30.M74BCx0zlZWeLIVh7td0LQjtLDB5KezBsJs51Q0n9nE

{
  "title": "Updated Title",
  "content": "Updated content of tshe post.",
  "author": "677a80d6c981245c5455a687"
  
}

### delete a post with an access token

DELETE http://localhost:3000/post/677a8a8ec74320900f37d65b
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NzdhODBkNmM5ODEyNDVjNTQ1NWE2ODciLCJpYXQiOjE3MzYwODQwMTYsImV4cCI6MTczNjE3MDQxNn0.9I-SFl0Tvw8N-_hxNRbhl2V0Uqaiau4ES70soN6qwIA

### Create a new comment with an access token
POST http://localhost:3000/comment
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NzdlNjU1MjYyNGY1NGUyMmM3ZTkwNTUiLCJpYXQiOjE3MzYzMzY3NDMsImV4cCI6MTczNjU5NTk0M30.M74BCx0zlZWeLIVh7td0LQjtLDB5KezBsJs51Q0n9nE

{
  "postId": "677df1e4bc98dc01f6bb410c",
  "content": "This is a comment on the postttttttttttt.",
  "author": "677a80d6c981245c5455a687"
}

### Update a comment with an access token
PUT http://localhost:3000/comment/677a8ed59fe1036c9b6ea28c
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NzdhOGQyNTlmZTEwMzZjOWI2ZWEyN2YiLCJpYXQiOjE3MzYwODQ3ODAsImV4cCI6MTczNjE3MTE4MH0.d5BuvijRRBzKkeBc6DU2vCgw0UvE6z2OV72Qb0tBrVw

{
  "content": "Updated comment content."
}

### Delete a comment with an access token
DELETE http://localhost:3000/comment/677a8ed59fe1036c9b6ea28c
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NzdhOGQyNTlmZTEwMzZjOWI2ZWEyN2YiLCJpYXQiOjE3MzYwODQ3ODAsImV4cCI6MTczNjE3MTE4MH0.d5BuvijRRBzKkeBc6DU2vCgw0UvE6z2OV72Qb0tBrVw

